python main.py \
  --dataset_name livecodebench \
  --model_name openai/o4-mini-2025-04-16 \
  --model_api_file /home/zhuwangz/miaosenchai/rescue_code_bench/keys/openai_key.txt\
  --input_file /home/zhuwangz/miaosenchai/GenerationDataset/LiveCodeBench/output/GPT-4O-2024-08-06-Old/false_livecode_gpt4o.json\
  --log_prefix  false_livecode\
  --output_prefix buggy_code \
  --max_iter 1 \
  --bug_per_time 5 \
  --max_id_count 338 \
  --temperature 1
