python main.py \
  --dataset_name kodcodebench \
  --model_name openai/gpt-4o-2024-08-06 \
  --model_api_file openai_key.txt\
  --input_file KodCode-V1/train-00000-of-00015.json\
  --log_prefix log \
  --output_prefix buggy_code \
  --rewrite \
  --max_iter 1 \
  --bug_per_time 3 \
  --max_id_count 1 \
  --temperature 0.7
